version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017" # Using external port 27018
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: news-api
    environment:
      - MONGO_URI=mongodb://mongo:27017/news
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
